# -*- coding: utf-8 -*-
"""count.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mN-5WT-ikwCB7GM16SIhKoaTPTeyluys
"""

import matplotlib.pyplot as plt

#Suppose we have the following data
T=[0,2,5,8,14,26]
time=[i for i in range (6)]
print(T)

#print a cumulative plot of claims against time
plt.figure()
plt.xlabel("Time (Month)")
plt.ylabel("Number of claims arrived")
plt.step(T,time,where='post')
plt.show()